#ifndef LMP_INSTALLED_PKGS_H
#define LMP_INSTALLED_PKGS_H
const char * LAMMPS_NS::LAMMPS::installed_packages[] = {
"ASPHERE",
"BODY",
"BROWNIAN",
"EXTRA-MOLECULE",
"EXTRA-PAIR",
"KSPACE",
"MANYBODY",
"MC",
"MEAM",
"MOLECULE",
"RIGID",
 NULL };
#endif
